src/js/backend.ts
The native install must be called with the full DSN including password.
Note that without the password the native install fails silently, and the error (*Invalid DSN, the following properties aren't set '[secret key]'*) is swallowed.
=> fix: call native install with DSN password

docs/ionic.rst, package.json
Fix *Could not find a declaration file for module 'sentry-cordova'* error when attempting to import Sentry into a TypeScript project, and fix a typo in the Ionic setup docs.
=> Fix typings

scripts/before_compile.js, scripts/plugin_add_rm.js
The usage of `requireCordovaModule` is deprecated and throws an error when used for requiring non `codova-` modules.
This change was introduced with `cordova>=9`.
See: https://github.com/apache/cordova-lib/pull/707
=> Remove usage of deprecated requireCordovaModule

scripts/before_compile.js
I figured out that Sentry wasn't getting our sourcemap because it was excluding our main bundle file.
```
appname.bundle.js
appname.bundle.js.map
```
The reason is that the includes walker assumes the main filename does not use a dot seaprator. It would parse *bundle* and *js* but never the *map* extension. It would also assume the main file extension was *bundle* in the example above.
This change reverses the array of filename _parts_, starting with the last extension, ensuring extensions are not overlooked. It does nothing to ensure the *name* part is complete because it is only used to exclude a single specific file.
After this change I noticed that one of my plugins was also being excluded from the upload becuase it too had a dot in the filename.
=> include source files with dot-separated names

scripts/before_compile.js
If `cordova prepare` and `cordova compile` are run independently, the paths array generated by prepare is not passed on to compile, and therefore not available to the `before_compile` script. This is normally not an issue if the user runs `cordova build` which runs prepare and compile in a promise chain with the same options object.
closes issue #122
=> fix: correct missing 'paths' element in before_compile context options

package.json, scripts/before_compile.js
Blindly using platforms/<platform>/www is not correct, as each platform can have the www folder in a different location. A more robust approach uses the platforms functionality of cordova-lib to obtain the path to the www folder.
This requires the cordova-lib NPM module, and I'm not familiar enough with the build process to know if this will work correctly when packaged for NPM (it does locally though).
=> fix: replicate cordova prepare functionality for getting platform paths

plugin.xml
If there is already more plugins in cordova project, it is useful to specify version in order to achieve each other compatibility.
I added config variable that allows to specify exact Sentry SDK version. It is possible to do that in config.xml like this:
<plugin name="sentry-cordova" spec="^0.16.2">
<variable name="SENTRY_ANDROID_SDK_VERSION" value="1.6.8" />
</plugin>
=> Added Android SDK version config variable

scripts/before_compile.js
This would have helped me know where to place the configuration
file while using Corber, a Cordova CLI.
I’m a near-novice in this realm so it may be that `ctx.opts.projectRoot` isn’t a reliable way to find what path to put the file at, but it worked for me, and I think it’s always nice to spell things out in this kind of situation.
Thanks for all the work on this! I ultimately found that any build I uploaded to TestFlight would open to a permanent blank screen so I switched to the JS-only version, but I couldn’t extract any logging or other helpful things that might facilitate debugging that problem, sadly.
=> Add path to place sentry.properties

plugin.xml
This properly copies source map file to the correct build directory.
Sorry, I could only test this in ios device. But should work in Android too.
Fixes #113
Fixes #163
Fixes #93
=> Fix source map file generating error

CHANGELOG.md, plugin.xml, src/android/io/sentry/SentryCordova.java
- Bumps Android SDK to v4.1.0
- Updates the call to init on the Android bridge
- Injects `auto-init` to be false to `AndroidManifest.xml`
Notes:
Bumps Android but we still send the event through the `BrowserBackend` and only send events through the native layer on iOS.
Addresses #185
Testing:
Tested on a simple sample app.
=> build(android): Bump Android SDK to v4.1.0

CHANGELOG.md, src/js/Ionic/SentryIonicErrorHandler.ts, src/js/__tests__/Ionic/SentryIonicErrorHandler.test.ts, src/js/sentry-cordova.ts
Adds a method that wraps the ionic global error handler instead of needing the user to manually extend it. This also makes the dead code we used to have here be used.
```js
// app.module.ts
const SentryIonicErrorHandler = Sentry.withSentryIonicErrorHandler(IonicErrorHandler);
@NgModule({
...
providers: [
StatusBar,
SplashScreen,
// {provide: ErrorHandler, useClass: IonicErrorHandler} remove this, add next line (for Ionic 4 this line doen't exist by default)
{provide: ErrorHandler, useClass: SentryIonicErrorHandler}
]
})
```
Tested on an Ionic sample app in chrome browser
We need to update the docs here: https://docs.sentry.io/platforms/javascript/guides/cordova/ionic/ to instead just have the user use this method.
=> feat: Add ionic global error handler wrapper method

package.json, yarn.lock
Resolves #169,
Also bumps the wizard to 1.1.4
=> build(js): Bump sentry-javascript dependencies to 6.1.0

src/android/io/sentry/SentryCordova.java, src/ios/SentryCordova.m, src/js/__tests__/wrapper.ts, src/js/transports/cordova.ts, src/js/types.ts, src/js/utils.ts, src/js/wrapper.ts
Uses the `window.cordova.platformId` global that's present on Cordova instead of calling into our native bridge and needing to await a promise to determine what platform it is being run on. This results in way cleaner code. Thus, this also removes the need to call into the native bridge (which we don't have a native module for, so it will throw an error that we catch) on browser and other platforms.
This `platformId` global has been there for [7 years or so, so it should be safe to use](https://github.com/apache/cordova-browser/blob/3b077ad590adc6f53a93b8af98efb20f8b1caeb7/cordova-lib/cordova.js#L180), but seems to not be documented anywhere.
This PR refactors how the native bridge checks whether the native SDK, native transport, and native scope sync is ready or not. We do this by …
=> ref: Use platformId global instead of calling into native layer getPlatform

.gitignore, CHANGELOG.md, src/ios/Cartfile, src/ios/Cartfile.resolved
=> build(ios): Bump sentry-cocoa to 6.2.1

CHANGELOG.md, src/android/io/sentry/SentryCordova.java, src/js/backend.ts, src/js/sdk.ts, src/js/sentry-cordova.ts, src/js/wrapper.ts
Complete Android native bridge module to be not just on par with React Native, with `setContext` support as well which RN does not have.
Features:
- Pass options to Android SDK
- Native Crash on Android for testing (Does not actually crash the app, but throws an error and we catch it)
- Add and clear Breadcrumbs 
- setUser, along with passing `null` to clear user
- setTag and setExtra
- setContext, pass `null` to clear a context.
- Write envelope to disk to support offline caching (Resolves #188)
Extra:
- As we add a `nativeCrash` method on the native wrapper on the JS side, this also enables native crash functionality on iOS. (Resolves #197)
Tested on a local Cordova sample app. (Should integrate this sample app into this repo at a later date)
=> feat(android): Add Android native bridge, full scope sync, and cached events

CHANGELOG.md, src/android/io/sentry/SentryCordova.java, src/ios/SentryCordova.m, src/js/client.ts
Sets `event.origin` and `event.environment` tags to be in line with `sentry-dart`.
They are set on the JS layer if the event comes from JS due to the events being sent through `captureEnvelope` on cocoa, which is not passed through `beforeSend`. ([Is this an issue on Flutter?](https://github.com/getsentry/sentry-dart/blob/ae21d7e44203fb544f97bd7b21b9bd2b4b779454/flutter/ios/Classes/SwiftSentryFlutterPlugin.swift#L205-L206))
=> feat: Set event.origin and event.environment tags

src/android/io/sentry/SentryCordova.java, src/ios/SentryCordova.m, src/js/wrapper.ts
Gets rid of the extra call across the native bridge that we used to have when we package the payload on the JS side with `getStringBytesLength`.
Also splits the iOS call into 2 parameters rather than a single object.
Originally wanted to unify `captureEnvelope` across the native bridge into a single call with the same parameters, but on iOS it needed the payload as an `NSDictionary` to pass to `NSJSONSerialization dataWithJSONObject` to get an NSData to create an envelope item. Tried this on Android, sending the payload over as a `JSONObject` and converting it into a string with `toString()`, however that outputted all the timestamps in scientific notation in the output JSON string (`x.xxxxxE9`) which errors the envelope pipeline. Considered using Gson instead, but I figured the …
=> ref: Get payload length in captureEnvelope on Android

CHANGELOG.md, src/ios/SentryCordova.m
Same as https://github.com/getsentry/sentry-react-native/pull/1308
Tested on iOS Simulator with sample app. With this, release health now works on the Cordova SDK for both iOS and Android. Browser will need a unique solution to use @sentry/browser's sessions while disabling it when running on native platforms. This will be added in a later version.
=> fix(ios): Handle auto session tracking start on iOS

CHANGELOG.md, src/ios/SentryCordova.m
Cordova passes the values as `NSNull` and not `nil` like on React Native.
Fixes #203 
Tested on Cordova sample app that after setting the user on the scope, calling `setUser` on the JS layer with `null` clears the user on iOS in a native crash.
=> fix: Support clearing user with null on iOS native bridge

CHANGELOG.md, src/js/sentry-cordova.ts
Expose `startTransaction` to use with `@sentry/tracing`. You will be able to just add tracing as a dependency, import it, and use it as if on browser after this method is exposed.
=> feat: Expose startTransaction

scripts/before_compile.js
This PR passes platformRootDir so the before_compile script doesn't fail.
=> Fix support for running with cordova-android 10

CHANGELOG.md, Makefile, plugin.xml
This PR fixes the build on M1 devices by adding an universal bundle to XCode where it's able to find the appropriate binaries for each target.
Close #252
=> Fix Mac M1 build

.npmignore, CHANGELOG.md
This PR fixes the change where Sentry.xcframework was being excluded from the final package. One way to validate is to check if Sentry.xcframework is located on the generated artifact on the following path "src/ios/Carthage/Build/Sentry.xcframework"
Ideally we need some basic integration test to validate if the package is building :D 
Fixes #265
=> dont exclude Sentry.xcframework from npm

.github/workflows/build.yml, .npmignore, CHANGELOG.md
* Adds an additional step to validate if the generated artifact contains any Symbolic Link.
* Removes the packages containing Symbolic links.
=> Enhance package validation + Remove Symbolic Links

README.md
As stated on https://github.com/getsentry/sentry-capacitor/pull/168
In https://github.com/getsentry/sentry-capacitor/pull/167, I updated the logo to use white or black based on theme. While this works well for GitHub, it was pointed out to me that we also render these readme files on package registries, and some (including NPM) do not set their theme correctly. (See https://github.com/getsentry/sentry-electron/pull/479#issuecomment-1118755203)
Updating to use the purple Sentry logo instead, which renders well on both white and black backgrounds, and will work for both GitHub and NPM.
Sorry for the friction.
=> Rollback Update logo in readme

.github/workflows/build.yml
Based on https://github.com/getsentry/sentry-capacitor/pull/213
The goal is to check if there aren't any missing changes that weren't pushed by the developer, if so, a release could get stalled because there are uncommitted changes on the main branch.
=> Check yarn.lock is dirty

CHANGELOG.md, Makefile, package.json, plugin.xml, scripts/plugin_add_rm.js, src/ios/Cartfile, src/ios/SentryCordova.m, src/js/options.ts, src/js/sdk.ts, yarn.lock
This is a possible fix to the issue #311, previously the SDK wasn't being even build due to having an old sentry-cocoa SDK with unsupported minimum version of iOS...
Changes on the SDK
- Fix Wizard breaking iOS build (https://github.com/getsentry/sentry-wizard/pull/401)
- iOS build failing on the latest xCode because minimum MacOS deployiment has increased, requiring a bump on the Sentry Cocoa SDK.
- Sentry Cocoa SDK bumped from 7.27.1 to 8.9.3
- Add support for Sentry Private SDK.
- fix Carthage scripts with the new SDK and remove unused Swift code.
TODO:
=> Bump sentry-cocoa/ fix issue 311

CHANGELOG.md
The main branch contains wrong URLs pointing to a wizard PR where it should actually point to the cordova PR, this PR fixes that.
Also, I have changed the changelog parameter of maskAllText to true
=> Fix changelog pointing to wrong PR URL

.github/workflows/build.yml
Related to #365, getting rid of GH_RELEASE_PAT usage, but it seems like a privileged token is not required here
=> fix(): Use workflow token instead of release PAT

.npmignore, scripts/xcode-upload-debug-files.sh
Previously this file was bundled with sentry/wizard, after this change, the  following script will be linked to the sentry Cordova.
These are the following changes on the Script file compared to Wizard.
- More path options for sentry.properties.
- Use node path from .xcode.env when node is not found.
- Skip the integration if node isn't found, avoiding a build failure when running Sentry-CLI.
- Use a more modern approach to find where Sentry-CLI is located.
Depends on: https://github.com/getsentry/sentry-wizard/pull/694
#skip-changelog (changelog will be bumped once I bump Sentry Wizard here)
=> Ref:  Move and refactor upload symbol script from wizard to sentry cordova

CHANGELOG.md, scripts/before_compile.js
This PR introduces a  change that when we automatically upload the release source maps, we also inject the Debuh ID, making it easier to link the sourcemap with the projects, without the need to have matching dists anymore.
Tested locally and validated on the server:
https://us.sentry.io/api/0/projects/sentry-sdks/sentry-cordova/events/33bd11062feb4bdcbe4203c223e43d16/json/
https://sentry-sdks.sentry.io/issues/6533969814/?project=5627302&query=is%3Aunresolved%20issue.priority%3A%5Bhigh%2C%20medium%5D&referrer=issue-stream&sort=date&stream_index=0
=> Feat: Support for Debug ID

CHANGELOG.md, package.json, yarn.lock
The old version of Sentry/Cli wasn't working properly with source maps, now with the latest version it seems to be working just fine.
This version also prepares Sentry Cordova for the major bump to Sentry/Wizard since it no longer comes with Sentry/Cli.
No break changes were noted when migrating from sentry/cli v1 to v2
=> Bump sentry/cli

CHANGELOG.md, plugin.xml, sample/package.json, sample/yarn.lock
Fix was done inside the Java SDK bump (Google Play’s 16 KB page size compatibility requirement)
Minor fix: bump cordova-android on sample so it supports the latest SDK.
Fixes https://github.com/getsentry/sentry-cordova/issues/381
=> Fix Android 15 support

CHANGELOG.md, package.json, plugin.xml, src/js/version.ts
1.6.0 was released but it failed to release a new version.
This PR only syncs what was released on version 1.6.0 into main
=> release: 1.6.0

CHANGELOG.md, src/js/__tests__/integrations/sdkinfo.test.ts, src/js/integrations/sdkinfo.ts
Based on https://github.com/getsentry/sentry-javascript/pull/17364
original context;
```
This PR fixes a long-standing problem in the SDK where it would set incorrect information about when Relay should (not) infer IP addresses from sent envelope requests.
Previously, this was thought to be controlled by setting event.user.ip_address: '{{auto}}'. However, after an incident in Relay, it was determined that this is in fact not a reliably way to control IP inference. Instead, SDKs should set event.sdk.settings.infer_ip: 'auto' | 'never' (see closes https://github.com/getsentry/sentry-javascript/issues/16252).
Unfortunately, this wasn't implemented immediately but is taken care of in this PR.
(FWIW, the only reason why Relay continued to infer IP addresses for the JS SDK was because it is …
```
=> FIX: missing ip settings from SDK package
